In [77]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression

In [78]:
data=pd.read_csv('data/Pima_Indian_diabetes.csv')

In [79]:
data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.000000,148.000000,72.000000,35.0,0.0,33.600000,0.627,50.000000,1
1,1.000000,85.000000,66.000000,29.0,0.0,26.600000,0.351,31.000000,0
2,8.000000,183.000000,64.000000,0.0,0.0,23.300000,0.672,32.000000,1
3,1.000000,89.000000,66.000000,23.0,94.0,19.179925,0.167,21.000000,0
4,0.000000,137.000000,40.000000,35.0,168.0,43.100000,2.288,33.000000,1
5,5.000000,116.000000,74.000000,0.0,0.0,25.600000,0.201,30.000000,0
6,3.000000,78.000000,43.869346,32.0,88.0,31.000000,0.248,26.000000,1
7,10.000000,115.000000,0.000000,0.0,0.0,35.300000,0.134,29.000000,0
8,2.000000,197.000000,70.000000,45.0,543.0,30.500000,0.158,NaN,1
9,8.000000,125.000000,96.000000,NaN,0.0,0.000000,0.232,68.636341,1
10,4.000000,110.000000,92.000000,0.0,0.0,37.600000,0.191,30.000000,0
11,10.000000,168.000000,74.000000,0.0,0.0,38.000000,0.537,34.000000,1
12,10.000000,139.000000,75.828903,0.0,0.0,27.100000,1.441,57.000000,0
13,1.000000,189.000000,60.000000,23.0,846.0,30.100000,0.398,59.000000,1
14,5.000000,146.526788,72.000000,19.0,175.0,25.800000,0.587,51.000000,1
15,7.000000,100.000000,0.000000,0.0,0.0,30.000000,0.484,32.000000,1
16,0.000000,118.000000,84.000000,47.0,230.0,45.800000,0.551,31.000000,1
17,7.000000,107.000000,74.000000,0.0,0.0,29.600000,0.254,31.000000,1
18,NaN,103.000000,30.000000,38.0,83.0,43.300000,0.183,33.000000,0
19,1.000000,115.000000,70.000000,30.0,96.0,34.600000,0.529,32.000000,1
20,3.000000,126.000000,88.000000,41.0,235.0,39.300000,0.704,27.000000,0
21,8.000000,99.000000,84.000000,0.0,0.0,35.400000,0.388,50.000000,0
22,7.000000,196.000000,90.000000,0.0,0.0,39.800000,0.451,41.000000,1
23,9.000000,119.000000,80.000000,35.0,0.0,29.000000,0.263,29.000000,1
24,11.000000,143.000000,94.000000,33.0,146.0,36.600000,0.254,51.000000,1
25,10.000000,125.000000,70.000000,26.0,115.0,31.100000,0.205,41.000000,1
26,7.000000,147.000000,76.000000,0.0,0.0,39.400000,0.257,43.000000,1
27,1.000000,97.000000,66.000000,15.0,140.0,23.200000,0.487,22.000000,0
28,13.000000,145.000000,82.000000,19.0,110.0,22.200000,0.245,57.000000,0
29,NaN,79.173309,92.000000,NaN,0.0,34.100000,0.337,38.000000,0
...,...,...,...,...,...,...,...,...,...
738,-5.412815,NaN,60.000000,17.0,160.0,36.600000,0.453,21.000000,0
739,1.000000,102.000000,74.000000,0.0,0.0,39.500000,0.293,42.000000,1
740,NaN,120.000000,80.000000,37.0,150.0,42.300000,0.785,48.000000,1
741,3.000000,102.000000,44.000000,20.0,94.0,30.800000,0.400,26.000000,0
742,1.000000,109.000000,58.000000,18.0,116.0,28.500000,0.219,32.641218,0
743,9.000000,140.000000,94.000000,0.0,0.0,32.700000,0.734,45.000000,1
744,13.000000,153.000000,88.000000,37.0,140.0,40.600000,1.174,39.000000,0
745,12.000000,100.000000,84.000000,NaN,105.0,30.000000,0.488,46.000000,0
746,1.000000,147.000000,94.000000,41.0,0.0,49.300000,0.358,27.000000,1
747,1.000000,81.000000,74.000000,41.0,57.0,46.300000,1.096,32.000000,0
748,3.000000,187.000000,70.000000,22.0,200.0,36.400000,0.408,36.000000,1
749,6.000000,162.000000,62.000000,0.0,0.0,24.300000,0.178,NaN,1
750,4.000000,136.000000,64.455702,0.0,0.0,31.200000,1.182,22.000000,1
751,1.000000,121.000000,78.000000,39.0,74.0,39.000000,0.261,28.000000,0
752,3.000000,108.000000,62.000000,24.0,0.0,26.000000,0.223,25.000000,0
753,0.000000,181.000000,88.000000,44.0,510.0,43.300000,0.222,26.000000,1
754,8.000000,154.000000,78.000000,32.0,0.0,32.400000,0.443,45.000000,1
755,1.000000,128.000000,88.000000,39.0,110.0,36.500000,1.057,37.000000,1
756,7.000000,137.000000,90.000000,41.0,0.0,32.000000,0.391,39.000000,0
757,0.000000,123.000000,72.000000,0.0,0.0,36.300000,0.258,52.000000,1
758,1.000000,106.000000,76.000000,0.0,0.0,37.500000,0.197,26.000000,0
759,6.000000,190.000000,92.000000,0.0,0.0,35.500000,0.278,66.000000,1
760,2.000000,88.000000,58.000000,26.0,16.0,28.400000,0.766,22.000000,0
761,9.000000,170.000000,74.000000,31.0,0.0,44.000000,0.403,43.000000,1
762,16.047327,89.000000,62.000000,0.0,0.0,22.500000,0.142,33.000000,0
763,10.000000,101.000000,76.000000,48.0,180.0,32.900000,0.171,63.000000,0
764,2.000000,122.000000,70.000000,27.0,0.0,36.800000,0.340,27.000000,0
765,5.000000,121.000000,72.000000,23.0,112.0,26.200000,0.245,30.000000,0
766,1.000000,126.000000,60.000000,0.0,0.0,30.100000,0.349,47.000000,1
767,1.000000,93.000000,70.000000,31.0,0.0,30.400000,0.315,23.000000,0

In [80]:
data=data[data['Pregnancies']>0]

In [81]:
data[50:64]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
55,1.000000,73.000000,50.0,10.0,0.0,23.000000,0.248,21.0,0
56,7.000000,169.308148,68.0,39.0,304.0,37.700000,0.254,41.0,1
60,2.000000,84.000000,0.0,0.0,0.0,-1.272125,0.304,21.0,0
61,8.000000,133.000000,72.0,0.0,0.0,32.900000,0.270,39.0,1
62,14.810044,44.000000,62.0,0.0,0.0,25.000000,0.587,36.0,0
64,7.000000,114.000000,66.0,0.0,0.0,32.800000,0.258,42.0,1
65,5.000000,99.000000,74.0,27.0,0.0,29.000000,0.203,32.0,0
67,2.000000,69.446117,92.0,0.0,0.0,42.700000,0.845,54.0,0
68,1.000000,95.000000,66.0,13.0,38.0,19.600000,0.334,25.0,0
69,4.000000,146.000000,85.0,27.0,100.0,28.900000,0.189,27.0,0
70,2.000000,100.000000,66.0,20.0,90.0,32.900000,0.867,28.0,1
71,5.000000,139.000000,64.0,35.0,140.0,-16.288921,0.411,26.0,0
72,13.000000,126.000000,90.0,0.0,0.0,43.400000,0.583,42.0,1
73,4.000000,129.000000,86.0,NaN,270.0,35.100000,0.231,23.0,0

In [82]:
data=data[data['BMI']>=0]

In [83]:
data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.000000,148.000000,72.000000,35.000000,0.0,33.600000,0.627,50.000000,1
1,1.000000,85.000000,66.000000,29.000000,0.0,26.600000,0.351,31.000000,0
2,8.000000,183.000000,64.000000,0.000000,0.0,23.300000,0.672,32.000000,1
3,1.000000,89.000000,66.000000,23.000000,94.0,19.179925,0.167,21.000000,0
5,5.000000,116.000000,74.000000,0.000000,0.0,25.600000,0.201,30.000000,0
6,3.000000,78.000000,43.869346,32.000000,88.0,31.000000,0.248,26.000000,1
7,10.000000,115.000000,0.000000,0.000000,0.0,35.300000,0.134,29.000000,0
8,2.000000,197.000000,70.000000,45.000000,543.0,30.500000,0.158,NaN,1
9,8.000000,125.000000,96.000000,NaN,0.0,0.000000,0.232,68.636341,1
10,4.000000,110.000000,92.000000,0.000000,0.0,37.600000,0.191,30.000000,0
11,10.000000,168.000000,74.000000,0.000000,0.0,38.000000,0.537,34.000000,1
12,10.000000,139.000000,75.828903,0.000000,0.0,27.100000,1.441,57.000000,0
13,1.000000,189.000000,60.000000,23.000000,846.0,30.100000,0.398,59.000000,1
14,5.000000,146.526788,72.000000,19.000000,175.0,25.800000,0.587,51.000000,1
15,7.000000,100.000000,0.000000,0.000000,0.0,30.000000,0.484,32.000000,1
17,7.000000,107.000000,74.000000,0.000000,0.0,29.600000,0.254,31.000000,1
19,1.000000,115.000000,70.000000,30.000000,96.0,34.600000,0.529,32.000000,1
20,3.000000,126.000000,88.000000,41.000000,235.0,39.300000,0.704,27.000000,0
21,8.000000,99.000000,84.000000,0.000000,0.0,35.400000,0.388,50.000000,0
22,7.000000,196.000000,90.000000,0.000000,0.0,39.800000,0.451,41.000000,1
23,9.000000,119.000000,80.000000,35.000000,0.0,29.000000,0.263,29.000000,1
24,11.000000,143.000000,94.000000,33.000000,146.0,36.600000,0.254,51.000000,1
25,10.000000,125.000000,70.000000,26.000000,115.0,31.100000,0.205,41.000000,1
26,7.000000,147.000000,76.000000,0.000000,0.0,39.400000,0.257,43.000000,1
27,1.000000,97.000000,66.000000,15.000000,140.0,23.200000,0.487,22.000000,0
28,13.000000,145.000000,82.000000,19.000000,110.0,22.200000,0.245,57.000000,0
30,5.000000,109.000000,75.000000,26.000000,0.0,36.000000,0.546,60.000000,0
31,3.000000,158.000000,76.000000,36.000000,245.0,31.600000,0.851,28.000000,1
32,3.000000,88.000000,52.579280,11.000000,54.0,24.800000,0.267,22.000000,0
33,6.000000,92.000000,92.000000,0.000000,0.0,19.900000,0.188,28.000000,0
...,...,...,...,...,...,...,...,...,...
733,2.000000,106.000000,56.000000,27.000000,165.0,29.000000,0.426,22.000000,0
734,2.000000,105.000000,75.000000,0.000000,0.0,23.300000,0.560,53.000000,0
735,4.000000,95.000000,60.000000,22.726002,0.0,35.400000,0.284,28.000000,0
737,8.000000,65.000000,72.000000,23.000000,0.0,32.000000,0.600,42.000000,0
739,1.000000,102.000000,74.000000,0.000000,0.0,39.500000,0.293,42.000000,1
741,3.000000,102.000000,44.000000,20.000000,94.0,30.800000,0.400,26.000000,0
742,1.000000,109.000000,58.000000,18.000000,116.0,28.500000,0.219,32.641218,0
743,9.000000,140.000000,94.000000,0.000000,0.0,32.700000,0.734,45.000000,1
744,13.000000,153.000000,88.000000,37.000000,140.0,40.600000,1.174,39.000000,0
745,12.000000,100.000000,84.000000,NaN,105.0,30.000000,0.488,46.000000,0
746,1.000000,147.000000,94.000000,41.000000,0.0,49.300000,0.358,27.000000,1
747,1.000000,81.000000,74.000000,41.000000,57.0,46.300000,1.096,32.000000,0
748,3.000000,187.000000,70.000000,22.000000,200.0,36.400000,0.408,36.000000,1
749,6.000000,162.000000,62.000000,0.000000,0.0,24.300000,0.178,NaN,1
750,4.000000,136.000000,64.455702,0.000000,0.0,31.200000,1.182,22.000000,1
751,1.000000,121.000000,78.000000,39.000000,74.0,39.000000,0.261,28.000000,0
752,3.000000,108.000000,62.000000,24.000000,0.0,26.000000,0.223,25.000000,0
754,8.000000,154.000000,78.000000,32.000000,0.0,32.400000,0.443,45.000000,1
755,1.000000,128.000000,88.000000,39.000000,110.0,36.500000,1.057,37.000000,1
756,7.000000,137.000000,90.000000,41.000000,0.0,32.000000,0.391,39.000000,0
758,1.000000,106.000000,76.000000,0.000000,0.0,37.500000,0.197,26.000000,0
759,6.000000,190.000000,92.000000,0.000000,0.0,35.500000,0.278,66.000000,1
760,2.000000,88.000000,58.000000,26.000000,16.0,28.400000,0.766,22.000000,0
761,9.000000,170.000000,74.000000,31.000000,0.0,44.000000,0.403,43.000000,1
762,16.047327,89.000000,62.000000,0.000000,0.0,22.500000,0.142,33.000000,0
763,10.000000,101.000000,76.000000,48.000000,180.0,32.900000,0.171,63.000000,0
764,2.000000,122.000000,70.000000,27.000000,0.0,36.800000,0.340,27.000000,0
765,5.000000,121.000000,72.000000,23.000000,112.0,26.200000,0.245,30.000000,0
766,1.000000,126.000000,60.000000,0.000000,0.0,30.100000,0.349,47.000000,1
767,1.000000,93.000000,70.000000,31.000000,0.0,30.400000,0.315,23.000000,0

In [84]:
data.BMI.isnull().sum()

0

In [85]:
BMI_mean = data.BMI.mean()

In [86]:

data.BMI.fillna(value = BMI_mean, inplace = True)

In [87]:
data.BMI.isnull().sum()

0

In [88]:
data.BMI=data.BMI.astype(int)

In [89]:
data.SkinThickness.isnull().sum()

16

In [90]:
skin_mean = data.SkinThickness.mean()

In [91]:
data.SkinThickness.fillna(value = skin_mean, inplace = True)

In [92]:
data.SkinThickness.isnull().sum()

0

In [93]:
data.Age.isnull().sum()

16

In [94]:
age_mean = data.Age.mean()

In [95]:
data.Age.fillna(value = age_mean, inplace = True)

In [96]:
data.Age.isnull().sum()

0

In [97]:
data.Pregnancies=data.Pregnancies.astype(int)

In [98]:
data.Age=data.Age.astype(int)

In [99]:
data.Glucose.isnull().sum()

13

In [100]:
gl_mean = data.Glucose.mean()

In [101]:
data.Glucose.fillna(value = gl_mean, inplace = True)

In [102]:
data.dropna()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.000000,72.000000,35.000000,0.0,33,0.627,50,1
1,1,85.000000,66.000000,29.000000,0.0,26,0.351,31,0
2,8,183.000000,64.000000,0.000000,0.0,23,0.672,32,1
3,1,89.000000,66.000000,23.000000,94.0,19,0.167,21,0
5,5,116.000000,74.000000,0.000000,0.0,25,0.201,30,0
6,3,78.000000,43.869346,32.000000,88.0,31,0.248,26,1
7,10,115.000000,0.000000,0.000000,0.0,35,0.134,29,0
8,2,197.000000,70.000000,45.000000,543.0,30,0.158,34,1
9,8,125.000000,96.000000,20.037237,0.0,0,0.232,68,1
10,4,110.000000,92.000000,0.000000,0.0,37,0.191,30,0
11,10,168.000000,74.000000,0.000000,0.0,38,0.537,34,1
12,10,139.000000,75.828903,0.000000,0.0,27,1.441,57,0
13,1,189.000000,60.000000,23.000000,846.0,30,0.398,59,1
14,5,146.526788,72.000000,19.000000,175.0,25,0.587,51,1
15,7,100.000000,0.000000,0.000000,0.0,30,0.484,32,1
17,7,107.000000,74.000000,0.000000,0.0,29,0.254,31,1
19,1,115.000000,70.000000,30.000000,96.0,34,0.529,32,1
20,3,126.000000,88.000000,41.000000,235.0,39,0.704,27,0
21,8,99.000000,84.000000,0.000000,0.0,35,0.388,50,0
22,7,196.000000,90.000000,0.000000,0.0,39,0.451,41,1
23,9,119.000000,80.000000,35.000000,0.0,29,0.263,29,1
24,11,143.000000,94.000000,33.000000,146.0,36,0.254,51,1
25,10,125.000000,70.000000,26.000000,115.0,31,0.205,41,1
26,7,147.000000,76.000000,0.000000,0.0,39,0.257,43,1
27,1,97.000000,66.000000,15.000000,140.0,23,0.487,22,0
28,13,145.000000,82.000000,19.000000,110.0,22,0.245,57,0
30,5,109.000000,75.000000,26.000000,0.0,36,0.546,60,0
31,3,158.000000,76.000000,36.000000,245.0,31,0.851,28,1
32,3,88.000000,52.579280,11.000000,54.0,24,0.267,22,0
33,6,92.000000,92.000000,0.000000,0.0,19,0.188,28,0
...,...,...,...,...,...,...,...,...,...
733,2,106.000000,56.000000,27.000000,165.0,29,0.426,22,0
734,2,105.000000,75.000000,0.000000,0.0,23,0.560,53,0
735,4,95.000000,60.000000,22.726002,0.0,35,0.284,28,0
737,8,65.000000,72.000000,23.000000,0.0,32,0.600,42,0
739,1,102.000000,74.000000,0.000000,0.0,39,0.293,42,1
741,3,102.000000,44.000000,20.000000,94.0,30,0.400,26,0
742,1,109.000000,58.000000,18.000000,116.0,28,0.219,32,0
743,9,140.000000,94.000000,0.000000,0.0,32,0.734,45,1
744,13,153.000000,88.000000,37.000000,140.0,40,1.174,39,0
745,12,100.000000,84.000000,20.037237,105.0,30,0.488,46,0
746,1,147.000000,94.000000,41.000000,0.0,49,0.358,27,1
747,1,81.000000,74.000000,41.000000,57.0,46,1.096,32,0
748,3,187.000000,70.000000,22.000000,200.0,36,0.408,36,1
749,6,162.000000,62.000000,0.000000,0.0,24,0.178,34,1
750,4,136.000000,64.455702,0.000000,0.0,31,1.182,22,1
751,1,121.000000,78.000000,39.000000,74.0,39,0.261,28,0
752,3,108.000000,62.000000,24.000000,0.0,26,0.223,25,0
754,8,154.000000,78.000000,32.000000,0.0,32,0.443,45,1
755,1,128.000000,88.000000,39.000000,110.0,36,1.057,37,1
756,7,137.000000,90.000000,41.000000,0.0,32,0.391,39,0
758,1,106.000000,76.000000,0.000000,0.0,37,0.197,26,0
759,6,190.000000,92.000000,0.000000,0.0,35,0.278,66,1
760,2,88.000000,58.000000,26.000000,16.0,28,0.766,22,0
761,9,170.000000,74.000000,31.000000,0.0,44,0.403,43,1
762,16,89.000000,62.000000,0.000000,0.0,22,0.142,33,0
763,10,101.000000,76.000000,48.000000,180.0,32,0.171,63,0
764,2,122.000000,70.000000,27.000000,0.0,36,0.340,27,0
765,5,121.000000,72.000000,23.000000,112.0,26,0.245,30,0
766,1,126.000000,60.000000,0.000000,0.0,30,0.349,47,1
767,1,93.000000,70.000000,31.000000,0.0,30,0.315,23,0

In [103]:
corr = data.corr()
print(corr)
sns.heatmap(corr, 
         xticklabels=corr.columns, 
         yticklabels=corr.columns)

                          Pregnancies   Glucose  BloodPressure  SkinThickness  \
Pregnancies                  1.000000  0.122079       0.128777      -0.100105
Glucose                      0.122079  1.000000       0.156452       0.036794
BloodPressure                0.128777  0.156452       1.000000       0.182649
SkinThickness               -0.100105  0.036794       0.182649       1.000000
Insulin                     -0.118074  0.331236       0.075477       0.421340
BMI                          0.056492  0.179791       0.306866       0.357922
DiabetesPedigreeFunction    -0.021918  0.095693       0.062693       0.184532
Age                          0.490289  0.274201       0.246168      -0.095954
Outcome                      0.233423  0.446902       0.093883       0.075642

                           Insulin       BMI  DiabetesPedigreeFunction  \
Pregnancies              -0.118074  0.056492                 -0.021918
Glucose                   0.331236  0.179791                  0.095693
BloodPressure             0.075477  0.306866                  0.062693
SkinThickness             0.421340  0.357922                  0.184532
Insulin                   1.000000  0.176955                  0.222223
BMI                       0.176955  1.000000                  0.151768
DiabetesPedigreeFunction  0.222223  0.151768                  1.000000
Age                      -0.025436  0.040300                  0.027723
Outcome                   0.143351  0.279609                  0.164363

                               Age   Outcome
Pregnancies               0.490289  0.233423
Glucose                   0.274201  0.446902
BloodPressure             0.246168  0.093883
SkinThickness            -0.095954  0.075642
Insulin                  -0.025436  0.143351
BMI                       0.040300  0.279609
DiabetesPedigreeFunction  0.027723  0.164363
Age                       1.000000  0.240580
Outcome                   0.240580  1.000000

NameError: name 'sns' is not defined

In [104]:
data.shape

(621, 9)

In [105]:
dfTrain = data[:550]
dfTest = data[551:600]
dfCheck = data[601:]

In [106]:
trainLabel = np.asarray(dfTrain['Outcome'])
trainData = np.asarray(dfTrain.drop('Outcome',1))
testLabel = np.asarray(dfTest['Outcome'])
testData = np.asarray(dfTest.drop('Outcome',1))

In [107]:

data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 621 entries, 0 to 767
Data columns (total 9 columns):
Pregnancies                 621 non-null int64
Glucose                     621 non-null float64
BloodPressure               621 non-null float64
SkinThickness               621 non-null float64
Insulin                     621 non-null float64
BMI                         621 non-null int64
DiabetesPedigreeFunction    621 non-null float64
Age                         621 non-null int64
Outcome                     621 non-null int64
dtypes: float64(5), int64(4)
memory usage: 48.5 KB

In [108]:
means = np.mean(trainData, axis=0)
stds = np.std(trainData, axis=0)
trainData = (trainData - means)/stds
testData = (testData - means)/stds



# drop rows with missing values

In [109]:
trainData<

SyntaxError: invalid syntax (<ipython-input-109-d83b278f57d3>, line 1)

In [110]:
from sklearn import svm

In [111]:
diabetesCheck = LogisticRegression()
diabetesCheck.fit(trainData, trainLabel)

/home/iiitb/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [112]:
data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.000000,72.000000,35.000000,0.0,33,0.627,50,1
1,1,85.000000,66.000000,29.000000,0.0,26,0.351,31,0
2,8,183.000000,64.000000,0.000000,0.0,23,0.672,32,1
3,1,89.000000,66.000000,23.000000,94.0,19,0.167,21,0
5,5,116.000000,74.000000,0.000000,0.0,25,0.201,30,0
6,3,78.000000,43.869346,32.000000,88.0,31,0.248,26,1
7,10,115.000000,0.000000,0.000000,0.0,35,0.134,29,0
8,2,197.000000,70.000000,45.000000,543.0,30,0.158,34,1
9,8,125.000000,96.000000,20.037237,0.0,0,0.232,68,1
10,4,110.000000,92.000000,0.000000,0.0,37,0.191,30,0
11,10,168.000000,74.000000,0.000000,0.0,38,0.537,34,1
12,10,139.000000,75.828903,0.000000,0.0,27,1.441,57,0
13,1,189.000000,60.000000,23.000000,846.0,30,0.398,59,1
14,5,146.526788,72.000000,19.000000,175.0,25,0.587,51,1
15,7,100.000000,0.000000,0.000000,0.0,30,0.484,32,1
17,7,107.000000,74.000000,0.000000,0.0,29,0.254,31,1
19,1,115.000000,70.000000,30.000000,96.0,34,0.529,32,1
20,3,126.000000,88.000000,41.000000,235.0,39,0.704,27,0
21,8,99.000000,84.000000,0.000000,0.0,35,0.388,50,0
22,7,196.000000,90.000000,0.000000,0.0,39,0.451,41,1
23,9,119.000000,80.000000,35.000000,0.0,29,0.263,29,1
24,11,143.000000,94.000000,33.000000,146.0,36,0.254,51,1
25,10,125.000000,70.000000,26.000000,115.0,31,0.205,41,1
26,7,147.000000,76.000000,0.000000,0.0,39,0.257,43,1
27,1,97.000000,66.000000,15.000000,140.0,23,0.487,22,0
28,13,145.000000,82.000000,19.000000,110.0,22,0.245,57,0
30,5,109.000000,75.000000,26.000000,0.0,36,0.546,60,0
31,3,158.000000,76.000000,36.000000,245.0,31,0.851,28,1
32,3,88.000000,52.579280,11.000000,54.0,24,0.267,22,0
33,6,92.000000,92.000000,0.000000,0.0,19,0.188,28,0
...,...,...,...,...,...,...,...,...,...
733,2,106.000000,56.000000,27.000000,165.0,29,0.426,22,0
734,2,105.000000,75.000000,0.000000,0.0,23,0.560,53,0
735,4,95.000000,60.000000,22.726002,0.0,35,0.284,28,0
737,8,65.000000,72.000000,23.000000,0.0,32,0.600,42,0
739,1,102.000000,74.000000,0.000000,0.0,39,0.293,42,1
741,3,102.000000,44.000000,20.000000,94.0,30,0.400,26,0
742,1,109.000000,58.000000,18.000000,116.0,28,0.219,32,0
743,9,140.000000,94.000000,0.000000,0.0,32,0.734,45,1
744,13,153.000000,88.000000,37.000000,140.0,40,1.174,39,0
745,12,100.000000,84.000000,20.037237,105.0,30,0.488,46,0
746,1,147.000000,94.000000,41.000000,0.0,49,0.358,27,1
747,1,81.000000,74.000000,41.000000,57.0,46,1.096,32,0
748,3,187.000000,70.000000,22.000000,200.0,36,0.408,36,1
749,6,162.000000,62.000000,0.000000,0.0,24,0.178,34,1
750,4,136.000000,64.455702,0.000000,0.0,31,1.182,22,1
751,1,121.000000,78.000000,39.000000,74.0,39,0.261,28,0
752,3,108.000000,62.000000,24.000000,0.0,26,0.223,25,0
754,8,154.000000,78.000000,32.000000,0.0,32,0.443,45,1
755,1,128.000000,88.000000,39.000000,110.0,36,1.057,37,1
756,7,137.000000,90.000000,41.000000,0.0,32,0.391,39,0
758,1,106.000000,76.000000,0.000000,0.0,37,0.197,26,0
759,6,190.000000,92.000000,0.000000,0.0,35,0.278,66,1
760,2,88.000000,58.000000,26.000000,16.0,28,0.766,22,0
761,9,170.000000,74.000000,31.000000,0.0,44,0.403,43,1
762,16,89.000000,62.000000,0.000000,0.0,22,0.142,33,0
763,10,101.000000,76.000000,48.000000,180.0,32,0.171,63,0
764,2,122.000000,70.000000,27.000000,0.0,36,0.340,27,0
765,5,121.000000,72.000000,23.000000,112.0,26,0.245,30,0
766,1,126.000000,60.000000,0.000000,0.0,30,0.349,47,1
767,1,93.000000,70.000000,31.000000,0.0,30,0.315,23,0

In [113]:
accuracy = diabetesCheck.score(testData, testLabel)
print("accuracy = ", accuracy * 100, "%")

accuracy =  73.46938775510205 %