In [96]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression

In [97]:
data=pd.read_csv('data/Pima_Indian_diabetes.csv')

In [98]:
data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.000000,148.000000,72.000000,35.0,0.0,33.600000,0.627,50.000000,1
1,1.000000,85.000000,66.000000,29.0,0.0,26.600000,0.351,31.000000,0
2,8.000000,183.000000,64.000000,0.0,0.0,23.300000,0.672,32.000000,1
3,1.000000,89.000000,66.000000,23.0,94.0,19.179925,0.167,21.000000,0
4,0.000000,137.000000,40.000000,35.0,168.0,43.100000,2.288,33.000000,1
5,5.000000,116.000000,74.000000,0.0,0.0,25.600000,0.201,30.000000,0
6,3.000000,78.000000,43.869346,32.0,88.0,31.000000,0.248,26.000000,1
7,10.000000,115.000000,0.000000,0.0,0.0,35.300000,0.134,29.000000,0
8,2.000000,197.000000,70.000000,45.0,543.0,30.500000,0.158,NaN,1
9,8.000000,125.000000,96.000000,NaN,0.0,0.000000,0.232,68.636341,1
10,4.000000,110.000000,92.000000,0.0,0.0,37.600000,0.191,30.000000,0
11,10.000000,168.000000,74.000000,0.0,0.0,38.000000,0.537,34.000000,1
12,10.000000,139.000000,75.828903,0.0,0.0,27.100000,1.441,57.000000,0
13,1.000000,189.000000,60.000000,23.0,846.0,30.100000,0.398,59.000000,1
14,5.000000,146.526788,72.000000,19.0,175.0,25.800000,0.587,51.000000,1
15,7.000000,100.000000,0.000000,0.0,0.0,30.000000,0.484,32.000000,1
16,0.000000,118.000000,84.000000,47.0,230.0,45.800000,0.551,31.000000,1
17,7.000000,107.000000,74.000000,0.0,0.0,29.600000,0.254,31.000000,1
18,NaN,103.000000,30.000000,38.0,83.0,43.300000,0.183,33.000000,0
19,1.000000,115.000000,70.000000,30.0,96.0,34.600000,0.529,32.000000,1
20,3.000000,126.000000,88.000000,41.0,235.0,39.300000,0.704,27.000000,0
21,8.000000,99.000000,84.000000,0.0,0.0,35.400000,0.388,50.000000,0
22,7.000000,196.000000,90.000000,0.0,0.0,39.800000,0.451,41.000000,1
23,9.000000,119.000000,80.000000,35.0,0.0,29.000000,0.263,29.000000,1
24,11.000000,143.000000,94.000000,33.0,146.0,36.600000,0.254,51.000000,1
25,10.000000,125.000000,70.000000,26.0,115.0,31.100000,0.205,41.000000,1
26,7.000000,147.000000,76.000000,0.0,0.0,39.400000,0.257,43.000000,1
27,1.000000,97.000000,66.000000,15.0,140.0,23.200000,0.487,22.000000,0
28,13.000000,145.000000,82.000000,19.0,110.0,22.200000,0.245,57.000000,0
29,NaN,79.173309,92.000000,NaN,0.0,34.100000,0.337,38.000000,0
...,...,...,...,...,...,...,...,...,...
738,-5.412815,NaN,60.000000,17.0,160.0,36.600000,0.453,21.000000,0
739,1.000000,102.000000,74.000000,0.0,0.0,39.500000,0.293,42.000000,1
740,NaN,120.000000,80.000000,37.0,150.0,42.300000,0.785,48.000000,1
741,3.000000,102.000000,44.000000,20.0,94.0,30.800000,0.400,26.000000,0
742,1.000000,109.000000,58.000000,18.0,116.0,28.500000,0.219,32.641218,0
743,9.000000,140.000000,94.000000,0.0,0.0,32.700000,0.734,45.000000,1
744,13.000000,153.000000,88.000000,37.0,140.0,40.600000,1.174,39.000000,0
745,12.000000,100.000000,84.000000,NaN,105.0,30.000000,0.488,46.000000,0
746,1.000000,147.000000,94.000000,41.0,0.0,49.300000,0.358,27.000000,1
747,1.000000,81.000000,74.000000,41.0,57.0,46.300000,1.096,32.000000,0
748,3.000000,187.000000,70.000000,22.0,200.0,36.400000,0.408,36.000000,1
749,6.000000,162.000000,62.000000,0.0,0.0,24.300000,0.178,NaN,1
750,4.000000,136.000000,64.455702,0.0,0.0,31.200000,1.182,22.000000,1
751,1.000000,121.000000,78.000000,39.0,74.0,39.000000,0.261,28.000000,0
752,3.000000,108.000000,62.000000,24.0,0.0,26.000000,0.223,25.000000,0
753,0.000000,181.000000,88.000000,44.0,510.0,43.300000,0.222,26.000000,1
754,8.000000,154.000000,78.000000,32.0,0.0,32.400000,0.443,45.000000,1
755,1.000000,128.000000,88.000000,39.0,110.0,36.500000,1.057,37.000000,1
756,7.000000,137.000000,90.000000,41.0,0.0,32.000000,0.391,39.000000,0
757,0.000000,123.000000,72.000000,0.0,0.0,36.300000,0.258,52.000000,1
758,1.000000,106.000000,76.000000,0.0,0.0,37.500000,0.197,26.000000,0
759,6.000000,190.000000,92.000000,0.0,0.0,35.500000,0.278,66.000000,1
760,2.000000,88.000000,58.000000,26.0,16.0,28.400000,0.766,22.000000,0
761,9.000000,170.000000,74.000000,31.0,0.0,44.000000,0.403,43.000000,1
762,16.047327,89.000000,62.000000,0.0,0.0,22.500000,0.142,33.000000,0
763,10.000000,101.000000,76.000000,48.0,180.0,32.900000,0.171,63.000000,0
764,2.000000,122.000000,70.000000,27.0,0.0,36.800000,0.340,27.000000,0
765,5.000000,121.000000,72.000000,23.0,112.0,26.200000,0.245,30.000000,0
766,1.000000,126.000000,60.000000,0.0,0.0,30.100000,0.349,47.000000,1
767,1.000000,93.000000,70.000000,31.0,0.0,30.400000,0.315,23.000000,0

In [99]:
data.Pregnancies[data.Pregnancies < 0] = 0

/home/iiitb/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [100]:
data.Glucose[data.Glucose< 0] = 0

/home/iiitb/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [101]:
data.BloodPressure[data.BloodPressure < 0] = 0

/home/iiitb/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [102]:
data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.000000,148.000000,72.000000,35.0,0.0,33.600000,0.627,50.000000,1
1,1.000000,85.000000,66.000000,29.0,0.0,26.600000,0.351,31.000000,0
2,8.000000,183.000000,64.000000,0.0,0.0,23.300000,0.672,32.000000,1
3,1.000000,89.000000,66.000000,23.0,94.0,19.179925,0.167,21.000000,0
4,0.000000,137.000000,40.000000,35.0,168.0,43.100000,2.288,33.000000,1
5,5.000000,116.000000,74.000000,0.0,0.0,25.600000,0.201,30.000000,0
6,3.000000,78.000000,43.869346,32.0,88.0,31.000000,0.248,26.000000,1
7,10.000000,115.000000,0.000000,0.0,0.0,35.300000,0.134,29.000000,0
8,2.000000,197.000000,70.000000,45.0,543.0,30.500000,0.158,NaN,1
9,8.000000,125.000000,96.000000,NaN,0.0,0.000000,0.232,68.636341,1
10,4.000000,110.000000,92.000000,0.0,0.0,37.600000,0.191,30.000000,0
11,10.000000,168.000000,74.000000,0.0,0.0,38.000000,0.537,34.000000,1
12,10.000000,139.000000,75.828903,0.0,0.0,27.100000,1.441,57.000000,0
13,1.000000,189.000000,60.000000,23.0,846.0,30.100000,0.398,59.000000,1
14,5.000000,146.526788,72.000000,19.0,175.0,25.800000,0.587,51.000000,1
15,7.000000,100.000000,0.000000,0.0,0.0,30.000000,0.484,32.000000,1
16,0.000000,118.000000,84.000000,47.0,230.0,45.800000,0.551,31.000000,1
17,7.000000,107.000000,74.000000,0.0,0.0,29.600000,0.254,31.000000,1
18,NaN,103.000000,30.000000,38.0,83.0,43.300000,0.183,33.000000,0
19,1.000000,115.000000,70.000000,30.0,96.0,34.600000,0.529,32.000000,1
20,3.000000,126.000000,88.000000,41.0,235.0,39.300000,0.704,27.000000,0
21,8.000000,99.000000,84.000000,0.0,0.0,35.400000,0.388,50.000000,0
22,7.000000,196.000000,90.000000,0.0,0.0,39.800000,0.451,41.000000,1
23,9.000000,119.000000,80.000000,35.0,0.0,29.000000,0.263,29.000000,1
24,11.000000,143.000000,94.000000,33.0,146.0,36.600000,0.254,51.000000,1
25,10.000000,125.000000,70.000000,26.0,115.0,31.100000,0.205,41.000000,1
26,7.000000,147.000000,76.000000,0.0,0.0,39.400000,0.257,43.000000,1
27,1.000000,97.000000,66.000000,15.0,140.0,23.200000,0.487,22.000000,0
28,13.000000,145.000000,82.000000,19.0,110.0,22.200000,0.245,57.000000,0
29,NaN,79.173309,92.000000,NaN,0.0,34.100000,0.337,38.000000,0
...,...,...,...,...,...,...,...,...,...
738,0.000000,NaN,60.000000,17.0,160.0,36.600000,0.453,21.000000,0
739,1.000000,102.000000,74.000000,0.0,0.0,39.500000,0.293,42.000000,1
740,NaN,120.000000,80.000000,37.0,150.0,42.300000,0.785,48.000000,1
741,3.000000,102.000000,44.000000,20.0,94.0,30.800000,0.400,26.000000,0
742,1.000000,109.000000,58.000000,18.0,116.0,28.500000,0.219,32.641218,0
743,9.000000,140.000000,94.000000,0.0,0.0,32.700000,0.734,45.000000,1
744,13.000000,153.000000,88.000000,37.0,140.0,40.600000,1.174,39.000000,0
745,12.000000,100.000000,84.000000,NaN,105.0,30.000000,0.488,46.000000,0
746,1.000000,147.000000,94.000000,41.0,0.0,49.300000,0.358,27.000000,1
747,1.000000,81.000000,74.000000,41.0,57.0,46.300000,1.096,32.000000,0
748,3.000000,187.000000,70.000000,22.0,200.0,36.400000,0.408,36.000000,1
749,6.000000,162.000000,62.000000,0.0,0.0,24.300000,0.178,NaN,1
750,4.000000,136.000000,64.455702,0.0,0.0,31.200000,1.182,22.000000,1
751,1.000000,121.000000,78.000000,39.0,74.0,39.000000,0.261,28.000000,0
752,3.000000,108.000000,62.000000,24.0,0.0,26.000000,0.223,25.000000,0
753,0.000000,181.000000,88.000000,44.0,510.0,43.300000,0.222,26.000000,1
754,8.000000,154.000000,78.000000,32.0,0.0,32.400000,0.443,45.000000,1
755,1.000000,128.000000,88.000000,39.0,110.0,36.500000,1.057,37.000000,1
756,7.000000,137.000000,90.000000,41.0,0.0,32.000000,0.391,39.000000,0
757,0.000000,123.000000,72.000000,0.0,0.0,36.300000,0.258,52.000000,1
758,1.000000,106.000000,76.000000,0.0,0.0,37.500000,0.197,26.000000,0
759,6.000000,190.000000,92.000000,0.0,0.0,35.500000,0.278,66.000000,1
760,2.000000,88.000000,58.000000,26.0,16.0,28.400000,0.766,22.000000,0
761,9.000000,170.000000,74.000000,31.0,0.0,44.000000,0.403,43.000000,1
762,16.047327,89.000000,62.000000,0.0,0.0,22.500000,0.142,33.000000,0
763,10.000000,101.000000,76.000000,48.0,180.0,32.900000,0.171,63.000000,0
764,2.000000,122.000000,70.000000,27.0,0.0,36.800000,0.340,27.000000,0
765,5.000000,121.000000,72.000000,23.0,112.0,26.200000,0.245,30.000000,0
766,1.000000,126.000000,60.000000,0.0,0.0,30.100000,0.349,47.000000,1
767,1.000000,93.000000,70.000000,31.0,0.0,30.400000,0.315,23.000000,0

In [103]:
data.SkinThickness[data.SkinThickness < 0] = 0

/home/iiitb/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [104]:
data.Insulin[data.Insulin < 0] = 0

/home/iiitb/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [105]:
data.BMI[data.BMI < 0] = 0

/home/iiitb/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [106]:
data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.000000,148.000000,72.000000,35.0,0.0,33.600000,0.627,50.000000,1
1,1.000000,85.000000,66.000000,29.0,0.0,26.600000,0.351,31.000000,0
2,8.000000,183.000000,64.000000,0.0,0.0,23.300000,0.672,32.000000,1
3,1.000000,89.000000,66.000000,23.0,94.0,19.179925,0.167,21.000000,0
4,0.000000,137.000000,40.000000,35.0,168.0,43.100000,2.288,33.000000,1
5,5.000000,116.000000,74.000000,0.0,0.0,25.600000,0.201,30.000000,0
6,3.000000,78.000000,43.869346,32.0,88.0,31.000000,0.248,26.000000,1
7,10.000000,115.000000,0.000000,0.0,0.0,35.300000,0.134,29.000000,0
8,2.000000,197.000000,70.000000,45.0,543.0,30.500000,0.158,NaN,1
9,8.000000,125.000000,96.000000,NaN,0.0,0.000000,0.232,68.636341,1
10,4.000000,110.000000,92.000000,0.0,0.0,37.600000,0.191,30.000000,0
11,10.000000,168.000000,74.000000,0.0,0.0,38.000000,0.537,34.000000,1
12,10.000000,139.000000,75.828903,0.0,0.0,27.100000,1.441,57.000000,0
13,1.000000,189.000000,60.000000,23.0,846.0,30.100000,0.398,59.000000,1
14,5.000000,146.526788,72.000000,19.0,175.0,25.800000,0.587,51.000000,1
15,7.000000,100.000000,0.000000,0.0,0.0,30.000000,0.484,32.000000,1
16,0.000000,118.000000,84.000000,47.0,230.0,45.800000,0.551,31.000000,1
17,7.000000,107.000000,74.000000,0.0,0.0,29.600000,0.254,31.000000,1
18,NaN,103.000000,30.000000,38.0,83.0,43.300000,0.183,33.000000,0
19,1.000000,115.000000,70.000000,30.0,96.0,34.600000,0.529,32.000000,1
20,3.000000,126.000000,88.000000,41.0,235.0,39.300000,0.704,27.000000,0
21,8.000000,99.000000,84.000000,0.0,0.0,35.400000,0.388,50.000000,0
22,7.000000,196.000000,90.000000,0.0,0.0,39.800000,0.451,41.000000,1
23,9.000000,119.000000,80.000000,35.0,0.0,29.000000,0.263,29.000000,1
24,11.000000,143.000000,94.000000,33.0,146.0,36.600000,0.254,51.000000,1
25,10.000000,125.000000,70.000000,26.0,115.0,31.100000,0.205,41.000000,1
26,7.000000,147.000000,76.000000,0.0,0.0,39.400000,0.257,43.000000,1
27,1.000000,97.000000,66.000000,15.0,140.0,23.200000,0.487,22.000000,0
28,13.000000,145.000000,82.000000,19.0,110.0,22.200000,0.245,57.000000,0
29,NaN,79.173309,92.000000,NaN,0.0,34.100000,0.337,38.000000,0
...,...,...,...,...,...,...,...,...,...
738,0.000000,NaN,60.000000,17.0,160.0,36.600000,0.453,21.000000,0
739,1.000000,102.000000,74.000000,0.0,0.0,39.500000,0.293,42.000000,1
740,NaN,120.000000,80.000000,37.0,150.0,42.300000,0.785,48.000000,1
741,3.000000,102.000000,44.000000,20.0,94.0,30.800000,0.400,26.000000,0
742,1.000000,109.000000,58.000000,18.0,116.0,28.500000,0.219,32.641218,0
743,9.000000,140.000000,94.000000,0.0,0.0,32.700000,0.734,45.000000,1
744,13.000000,153.000000,88.000000,37.0,140.0,40.600000,1.174,39.000000,0
745,12.000000,100.000000,84.000000,NaN,105.0,30.000000,0.488,46.000000,0
746,1.000000,147.000000,94.000000,41.0,0.0,49.300000,0.358,27.000000,1
747,1.000000,81.000000,74.000000,41.0,57.0,46.300000,1.096,32.000000,0
748,3.000000,187.000000,70.000000,22.0,200.0,36.400000,0.408,36.000000,1
749,6.000000,162.000000,62.000000,0.0,0.0,24.300000,0.178,NaN,1
750,4.000000,136.000000,64.455702,0.0,0.0,31.200000,1.182,22.000000,1
751,1.000000,121.000000,78.000000,39.0,74.0,39.000000,0.261,28.000000,0
752,3.000000,108.000000,62.000000,24.0,0.0,26.000000,0.223,25.000000,0
753,0.000000,181.000000,88.000000,44.0,510.0,43.300000,0.222,26.000000,1
754,8.000000,154.000000,78.000000,32.0,0.0,32.400000,0.443,45.000000,1
755,1.000000,128.000000,88.000000,39.0,110.0,36.500000,1.057,37.000000,1
756,7.000000,137.000000,90.000000,41.0,0.0,32.000000,0.391,39.000000,0
757,0.000000,123.000000,72.000000,0.0,0.0,36.300000,0.258,52.000000,1
758,1.000000,106.000000,76.000000,0.0,0.0,37.500000,0.197,26.000000,0
759,6.000000,190.000000,92.000000,0.0,0.0,35.500000,0.278,66.000000,1
760,2.000000,88.000000,58.000000,26.0,16.0,28.400000,0.766,22.000000,0
761,9.000000,170.000000,74.000000,31.0,0.0,44.000000,0.403,43.000000,1
762,16.047327,89.000000,62.000000,0.0,0.0,22.500000,0.142,33.000000,0
763,10.000000,101.000000,76.000000,48.0,180.0,32.900000,0.171,63.000000,0
764,2.000000,122.000000,70.000000,27.0,0.0,36.800000,0.340,27.000000,0
765,5.000000,121.000000,72.000000,23.0,112.0,26.200000,0.245,30.000000,0
766,1.000000,126.000000,60.000000,0.0,0.0,30.100000,0.349,47.000000,1
767,1.000000,93.000000,70.000000,31.0,0.0,30.400000,0.315,23.000000,0

In [107]:
data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.000000,148.000000,72.000000,35.0,0.0,33.600000,0.627,50.000000,1
1,1.000000,85.000000,66.000000,29.0,0.0,26.600000,0.351,31.000000,0
2,8.000000,183.000000,64.000000,0.0,0.0,23.300000,0.672,32.000000,1
3,1.000000,89.000000,66.000000,23.0,94.0,19.179925,0.167,21.000000,0
4,0.000000,137.000000,40.000000,35.0,168.0,43.100000,2.288,33.000000,1
5,5.000000,116.000000,74.000000,0.0,0.0,25.600000,0.201,30.000000,0
6,3.000000,78.000000,43.869346,32.0,88.0,31.000000,0.248,26.000000,1
7,10.000000,115.000000,0.000000,0.0,0.0,35.300000,0.134,29.000000,0
8,2.000000,197.000000,70.000000,45.0,543.0,30.500000,0.158,NaN,1
9,8.000000,125.000000,96.000000,NaN,0.0,0.000000,0.232,68.636341,1
10,4.000000,110.000000,92.000000,0.0,0.0,37.600000,0.191,30.000000,0
11,10.000000,168.000000,74.000000,0.0,0.0,38.000000,0.537,34.000000,1
12,10.000000,139.000000,75.828903,0.0,0.0,27.100000,1.441,57.000000,0
13,1.000000,189.000000,60.000000,23.0,846.0,30.100000,0.398,59.000000,1
14,5.000000,146.526788,72.000000,19.0,175.0,25.800000,0.587,51.000000,1
15,7.000000,100.000000,0.000000,0.0,0.0,30.000000,0.484,32.000000,1
16,0.000000,118.000000,84.000000,47.0,230.0,45.800000,0.551,31.000000,1
17,7.000000,107.000000,74.000000,0.0,0.0,29.600000,0.254,31.000000,1
18,NaN,103.000000,30.000000,38.0,83.0,43.300000,0.183,33.000000,0
19,1.000000,115.000000,70.000000,30.0,96.0,34.600000,0.529,32.000000,1
20,3.000000,126.000000,88.000000,41.0,235.0,39.300000,0.704,27.000000,0
21,8.000000,99.000000,84.000000,0.0,0.0,35.400000,0.388,50.000000,0
22,7.000000,196.000000,90.000000,0.0,0.0,39.800000,0.451,41.000000,1
23,9.000000,119.000000,80.000000,35.0,0.0,29.000000,0.263,29.000000,1
24,11.000000,143.000000,94.000000,33.0,146.0,36.600000,0.254,51.000000,1
25,10.000000,125.000000,70.000000,26.0,115.0,31.100000,0.205,41.000000,1
26,7.000000,147.000000,76.000000,0.0,0.0,39.400000,0.257,43.000000,1
27,1.000000,97.000000,66.000000,15.0,140.0,23.200000,0.487,22.000000,0
28,13.000000,145.000000,82.000000,19.0,110.0,22.200000,0.245,57.000000,0
29,NaN,79.173309,92.000000,NaN,0.0,34.100000,0.337,38.000000,0
...,...,...,...,...,...,...,...,...,...
738,0.000000,NaN,60.000000,17.0,160.0,36.600000,0.453,21.000000,0
739,1.000000,102.000000,74.000000,0.0,0.0,39.500000,0.293,42.000000,1
740,NaN,120.000000,80.000000,37.0,150.0,42.300000,0.785,48.000000,1
741,3.000000,102.000000,44.000000,20.0,94.0,30.800000,0.400,26.000000,0
742,1.000000,109.000000,58.000000,18.0,116.0,28.500000,0.219,32.641218,0
743,9.000000,140.000000,94.000000,0.0,0.0,32.700000,0.734,45.000000,1
744,13.000000,153.000000,88.000000,37.0,140.0,40.600000,1.174,39.000000,0
745,12.000000,100.000000,84.000000,NaN,105.0,30.000000,0.488,46.000000,0
746,1.000000,147.000000,94.000000,41.0,0.0,49.300000,0.358,27.000000,1
747,1.000000,81.000000,74.000000,41.0,57.0,46.300000,1.096,32.000000,0
748,3.000000,187.000000,70.000000,22.0,200.0,36.400000,0.408,36.000000,1
749,6.000000,162.000000,62.000000,0.0,0.0,24.300000,0.178,NaN,1
750,4.000000,136.000000,64.455702,0.0,0.0,31.200000,1.182,22.000000,1
751,1.000000,121.000000,78.000000,39.0,74.0,39.000000,0.261,28.000000,0
752,3.000000,108.000000,62.000000,24.0,0.0,26.000000,0.223,25.000000,0
753,0.000000,181.000000,88.000000,44.0,510.0,43.300000,0.222,26.000000,1
754,8.000000,154.000000,78.000000,32.0,0.0,32.400000,0.443,45.000000,1
755,1.000000,128.000000,88.000000,39.0,110.0,36.500000,1.057,37.000000,1
756,7.000000,137.000000,90.000000,41.0,0.0,32.000000,0.391,39.000000,0
757,0.000000,123.000000,72.000000,0.0,0.0,36.300000,0.258,52.000000,1
758,1.000000,106.000000,76.000000,0.0,0.0,37.500000,0.197,26.000000,0
759,6.000000,190.000000,92.000000,0.0,0.0,35.500000,0.278,66.000000,1
760,2.000000,88.000000,58.000000,26.0,16.0,28.400000,0.766,22.000000,0
761,9.000000,170.000000,74.000000,31.0,0.0,44.000000,0.403,43.000000,1
762,16.047327,89.000000,62.000000,0.0,0.0,22.500000,0.142,33.000000,0
763,10.000000,101.000000,76.000000,48.0,180.0,32.900000,0.171,63.000000,0
764,2.000000,122.000000,70.000000,27.0,0.0,36.800000,0.340,27.000000,0
765,5.000000,121.000000,72.000000,23.0,112.0,26.200000,0.245,30.000000,0
766,1.000000,126.000000,60.000000,0.0,0.0,30.100000,0.349,47.000000,1
767,1.000000,93.000000,70.000000,31.0,0.0,30.400000,0.315,23.000000,0

In [108]:

data.shape

(768, 9)

In [109]:
data.BMI.isnull().sum()

11

In [110]:
BMI_mean = data.BMI.mean()

In [111]:

data.BMI.fillna(value = BMI_mean, inplace = True)

In [112]:
data.BMI.isnull().sum()

0

In [113]:
data.BMI=data.BMI.astype(int)

In [114]:
data.SkinThickness.isnull().sum()

22

In [115]:
skin_mean = data.SkinThickness.mean()

In [117]:
data.loc[data.SkinThickness==0.0,"SkinThickness"]=skin_mean

In [118]:
data.SkinThickness.fillna(value = skin_mean, inplace = True)

In [119]:
data.SkinThickness.isnull().sum()

0

In [120]:
data.Age.isnull().sum()

19

In [121]:
age_mean = data.Age.mean()

In [122]:
data.Age.fillna(value = age_mean, inplace = True)

In [123]:
data.Age.isnull().sum()

0

In [124]:
data.Pregnancies=data.Pregnancies.astype(int)

ValueError: Cannot convert non-finite values (NA or inf) to integer

In [125]:
data.Age=data.Age.astype(int)

In [126]:
data.Glucose.isnull().sum()

16

In [127]:
gl_mean = data.Glucose.mean()

In [128]:
data.Glucose.fillna(value = gl_mean, inplace = True)

In [129]:
insulin_mean = data.Insulin.mean()

In [130]:
data.loc[data.Insulin==0.0,"Insulin"]=insulin_mean

In [131]:
data.dropna()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.000000,148.000000,72.000000,35.000000,79.799479,33,0.627,50,1
1,1.000000,85.000000,66.000000,29.000000,79.799479,26,0.351,31,0
2,8.000000,183.000000,64.000000,20.358987,79.799479,23,0.672,32,1
3,1.000000,89.000000,66.000000,23.000000,94.000000,19,0.167,21,0
4,0.000000,137.000000,40.000000,35.000000,168.000000,43,2.288,33,1
5,5.000000,116.000000,74.000000,20.358987,79.799479,25,0.201,30,0
6,3.000000,78.000000,43.869346,32.000000,88.000000,31,0.248,26,1
7,10.000000,115.000000,0.000000,20.358987,79.799479,35,0.134,29,0
8,2.000000,197.000000,70.000000,45.000000,543.000000,30,0.158,33,1
9,8.000000,125.000000,96.000000,20.358987,79.799479,0,0.232,68,1
10,4.000000,110.000000,92.000000,20.358987,79.799479,37,0.191,30,0
11,10.000000,168.000000,74.000000,20.358987,79.799479,38,0.537,34,1
12,10.000000,139.000000,75.828903,20.358987,79.799479,27,1.441,57,0
13,1.000000,189.000000,60.000000,23.000000,846.000000,30,0.398,59,1
14,5.000000,146.526788,72.000000,19.000000,175.000000,25,0.587,51,1
15,7.000000,100.000000,0.000000,20.358987,79.799479,30,0.484,32,1
16,0.000000,118.000000,84.000000,47.000000,230.000000,45,0.551,31,1
17,7.000000,107.000000,74.000000,20.358987,79.799479,29,0.254,31,1
19,1.000000,115.000000,70.000000,30.000000,96.000000,34,0.529,32,1
20,3.000000,126.000000,88.000000,41.000000,235.000000,39,0.704,27,0
21,8.000000,99.000000,84.000000,20.358987,79.799479,35,0.388,50,0
22,7.000000,196.000000,90.000000,20.358987,79.799479,39,0.451,41,1
23,9.000000,119.000000,80.000000,35.000000,79.799479,29,0.263,29,1
24,11.000000,143.000000,94.000000,33.000000,146.000000,36,0.254,51,1
25,10.000000,125.000000,70.000000,26.000000,115.000000,31,0.205,41,1
26,7.000000,147.000000,76.000000,20.358987,79.799479,39,0.257,43,1
27,1.000000,97.000000,66.000000,15.000000,140.000000,23,0.487,22,0
28,13.000000,145.000000,82.000000,19.000000,110.000000,22,0.245,57,0
30,5.000000,109.000000,75.000000,26.000000,79.799479,36,0.546,60,0
31,3.000000,158.000000,76.000000,36.000000,245.000000,31,0.851,28,1
...,...,...,...,...,...,...,...,...,...
737,8.000000,65.000000,72.000000,23.000000,79.799479,32,0.600,42,0
738,0.000000,119.966097,60.000000,17.000000,160.000000,36,0.453,21,0
739,1.000000,102.000000,74.000000,20.358987,79.799479,39,0.293,42,1
741,3.000000,102.000000,44.000000,20.000000,94.000000,30,0.400,26,0
742,1.000000,109.000000,58.000000,18.000000,116.000000,28,0.219,32,0
743,9.000000,140.000000,94.000000,20.358987,79.799479,32,0.734,45,1
744,13.000000,153.000000,88.000000,37.000000,140.000000,40,1.174,39,0
745,12.000000,100.000000,84.000000,20.358987,105.000000,30,0.488,46,0
746,1.000000,147.000000,94.000000,41.000000,79.799479,49,0.358,27,1
747,1.000000,81.000000,74.000000,41.000000,57.000000,46,1.096,32,0
748,3.000000,187.000000,70.000000,22.000000,200.000000,36,0.408,36,1
749,6.000000,162.000000,62.000000,20.358987,79.799479,24,0.178,33,1
750,4.000000,136.000000,64.455702,20.358987,79.799479,31,1.182,22,1
751,1.000000,121.000000,78.000000,39.000000,74.000000,39,0.261,28,0
752,3.000000,108.000000,62.000000,24.000000,79.799479,26,0.223,25,0
753,0.000000,181.000000,88.000000,44.000000,510.000000,43,0.222,26,1
754,8.000000,154.000000,78.000000,32.000000,79.799479,32,0.443,45,1
755,1.000000,128.000000,88.000000,39.000000,110.000000,36,1.057,37,1
756,7.000000,137.000000,90.000000,41.000000,79.799479,32,0.391,39,0
757,0.000000,123.000000,72.000000,20.358987,79.799479,36,0.258,52,1
758,1.000000,106.000000,76.000000,20.358987,79.799479,37,0.197,26,0
759,6.000000,190.000000,92.000000,20.358987,79.799479,35,0.278,66,1
760,2.000000,88.000000,58.000000,26.000000,16.000000,28,0.766,22,0
761,9.000000,170.000000,74.000000,31.000000,79.799479,44,0.403,43,1
762,16.047327,89.000000,62.000000,20.358987,79.799479,22,0.142,33,0
763,10.000000,101.000000,76.000000,48.000000,180.000000,32,0.171,63,0
764,2.000000,122.000000,70.000000,27.000000,79.799479,36,0.340,27,0
765,5.000000,121.000000,72.000000,23.000000,112.000000,26,0.245,30,0
766,1.000000,126.000000,60.000000,20.358987,79.799479,30,0.349,47,1
767,1.000000,93.000000,70.000000,31.000000,79.799479,30,0.315,23,0

In [132]:
corr = data.corr()
print(corr)
sns.heatmap(corr, 
         xticklabels=corr.columns, 
         yticklabels=corr.columns)

                          Pregnancies   Glucose  BloodPressure  SkinThickness  \
Pregnancies                  1.000000  0.088641       0.122548      -0.006750
Glucose                      0.088641  1.000000       0.139927       0.155821
BloodPressure                0.122548  0.139927       1.000000       0.174695
SkinThickness               -0.006750  0.155821       0.174695       1.000000
Insulin                     -0.040565  0.385892       0.076439       0.229524
BMI                         -0.015074  0.182596       0.280019       0.460279
DiabetesPedigreeFunction    -0.039072  0.123538       0.040077       0.151436
Age                          0.463049  0.238085       0.228345      -0.008723
Outcome                      0.195926  0.465235       0.063583       0.172367

                           Insulin       BMI  DiabetesPedigreeFunction  \
Pregnancies              -0.040565 -0.015074                 -0.039072
Glucose                   0.385892  0.182596                  0.123538
BloodPressure             0.076439  0.280019                  0.040077
SkinThickness             0.229524  0.460279                  0.151436
Insulin                   1.000000  0.182586                  0.157806
BMI                       0.182586  1.000000                  0.149220
DiabetesPedigreeFunction  0.157806  0.149220                  1.000000
Age                       0.026753  0.019658                  0.037354
Outcome                   0.179185  0.280956                  0.173844

                               Age   Outcome
Pregnancies               0.463049  0.195926
Glucose                   0.238085  0.465235
BloodPressure             0.228345  0.063583
SkinThickness            -0.008723  0.172367
Insulin                   0.026753  0.179185
BMI                       0.019658  0.280956
DiabetesPedigreeFunction  0.037354  0.173844
Age                       1.000000  0.212716
Outcome                   0.212716  1.000000

NameError: name 'sns' is not defined

In [141]:
data.shape

(742, 9)

In [169]:
dfTrain = data[:600]
dfTest = data[:200]
dfCheck = data[721:]

In [170]:
trainLabel = np.asarray(dfTrain['Outcome'])
trainData = np.asarray(dfTrain.drop('Outcome',1))
testLabel = np.asarray(dfTest['Outcome'])
testData = np.asarray(dfTest.drop('Outcome',1))

In [171]:

data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 742 entries, 0 to 767
Data columns (total 9 columns):
Pregnancies                 742 non-null float64
Glucose                     742 non-null float64
BloodPressure               742 non-null float64
SkinThickness               742 non-null float64
Insulin                     742 non-null float64
BMI                         742 non-null int64
DiabetesPedigreeFunction    742 non-null float64
Age                         742 non-null int64
Outcome                     742 non-null int64
dtypes: float64(6), int64(3)
memory usage: 58.0 KB

In [172]:
data=data.dropna()

In [173]:
means = np.mean(trainData, axis=0)
stds = np.std(trainData, axis=0)
trainData = (trainData - means)/stds
testData = (testData - means)/stds



# drop rows with missing values

In [174]:
trainData<

SyntaxError: invalid syntax (<ipython-input-174-d83b278f57d3>, line 1)

In [175]:
data.shape

(742, 9)

In [176]:
from sklearn.svm import SVC

In [177]:
diabetesCheck = LogisticRegression()
diabetesCheck.fit(trainData, trainLabel)

/home/iiitb/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [178]:
data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.000000,148.000000,72.000000,35.000000,79.799479,33,0.627,50,1
1,1.000000,85.000000,66.000000,29.000000,79.799479,26,0.351,31,0
2,8.000000,183.000000,64.000000,20.358987,79.799479,23,0.672,32,1
3,1.000000,89.000000,66.000000,23.000000,94.000000,19,0.167,21,0
4,0.000000,137.000000,40.000000,35.000000,168.000000,43,2.288,33,1
5,5.000000,116.000000,74.000000,20.358987,79.799479,25,0.201,30,0
6,3.000000,78.000000,43.869346,32.000000,88.000000,31,0.248,26,1
7,10.000000,115.000000,0.000000,20.358987,79.799479,35,0.134,29,0
8,2.000000,197.000000,70.000000,45.000000,543.000000,30,0.158,33,1
9,8.000000,125.000000,96.000000,20.358987,79.799479,0,0.232,68,1
10,4.000000,110.000000,92.000000,20.358987,79.799479,37,0.191,30,0
11,10.000000,168.000000,74.000000,20.358987,79.799479,38,0.537,34,1
12,10.000000,139.000000,75.828903,20.358987,79.799479,27,1.441,57,0
13,1.000000,189.000000,60.000000,23.000000,846.000000,30,0.398,59,1
14,5.000000,146.526788,72.000000,19.000000,175.000000,25,0.587,51,1
15,7.000000,100.000000,0.000000,20.358987,79.799479,30,0.484,32,1
16,0.000000,118.000000,84.000000,47.000000,230.000000,45,0.551,31,1
17,7.000000,107.000000,74.000000,20.358987,79.799479,29,0.254,31,1
19,1.000000,115.000000,70.000000,30.000000,96.000000,34,0.529,32,1
20,3.000000,126.000000,88.000000,41.000000,235.000000,39,0.704,27,0
21,8.000000,99.000000,84.000000,20.358987,79.799479,35,0.388,50,0
22,7.000000,196.000000,90.000000,20.358987,79.799479,39,0.451,41,1
23,9.000000,119.000000,80.000000,35.000000,79.799479,29,0.263,29,1
24,11.000000,143.000000,94.000000,33.000000,146.000000,36,0.254,51,1
25,10.000000,125.000000,70.000000,26.000000,115.000000,31,0.205,41,1
26,7.000000,147.000000,76.000000,20.358987,79.799479,39,0.257,43,1
27,1.000000,97.000000,66.000000,15.000000,140.000000,23,0.487,22,0
28,13.000000,145.000000,82.000000,19.000000,110.000000,22,0.245,57,0
30,5.000000,109.000000,75.000000,26.000000,79.799479,36,0.546,60,0
31,3.000000,158.000000,76.000000,36.000000,245.000000,31,0.851,28,1
...,...,...,...,...,...,...,...,...,...
737,8.000000,65.000000,72.000000,23.000000,79.799479,32,0.600,42,0
738,0.000000,119.966097,60.000000,17.000000,160.000000,36,0.453,21,0
739,1.000000,102.000000,74.000000,20.358987,79.799479,39,0.293,42,1
741,3.000000,102.000000,44.000000,20.000000,94.000000,30,0.400,26,0
742,1.000000,109.000000,58.000000,18.000000,116.000000,28,0.219,32,0
743,9.000000,140.000000,94.000000,20.358987,79.799479,32,0.734,45,1
744,13.000000,153.000000,88.000000,37.000000,140.000000,40,1.174,39,0
745,12.000000,100.000000,84.000000,20.358987,105.000000,30,0.488,46,0
746,1.000000,147.000000,94.000000,41.000000,79.799479,49,0.358,27,1
747,1.000000,81.000000,74.000000,41.000000,57.000000,46,1.096,32,0
748,3.000000,187.000000,70.000000,22.000000,200.000000,36,0.408,36,1
749,6.000000,162.000000,62.000000,20.358987,79.799479,24,0.178,33,1
750,4.000000,136.000000,64.455702,20.358987,79.799479,31,1.182,22,1
751,1.000000,121.000000,78.000000,39.000000,74.000000,39,0.261,28,0
752,3.000000,108.000000,62.000000,24.000000,79.799479,26,0.223,25,0
753,0.000000,181.000000,88.000000,44.000000,510.000000,43,0.222,26,1
754,8.000000,154.000000,78.000000,32.000000,79.799479,32,0.443,45,1
755,1.000000,128.000000,88.000000,39.000000,110.000000,36,1.057,37,1
756,7.000000,137.000000,90.000000,41.000000,79.799479,32,0.391,39,0
757,0.000000,123.000000,72.000000,20.358987,79.799479,36,0.258,52,1
758,1.000000,106.000000,76.000000,20.358987,79.799479,37,0.197,26,0
759,6.000000,190.000000,92.000000,20.358987,79.799479,35,0.278,66,1
760,2.000000,88.000000,58.000000,26.000000,16.000000,28,0.766,22,0
761,9.000000,170.000000,74.000000,31.000000,79.799479,44,0.403,43,1
762,16.047327,89.000000,62.000000,20.358987,79.799479,22,0.142,33,0
763,10.000000,101.000000,76.000000,48.000000,180.000000,32,0.171,63,0
764,2.000000,122.000000,70.000000,27.000000,79.799479,36,0.340,27,0
765,5.000000,121.000000,72.000000,23.000000,112.000000,26,0.245,30,0
766,1.000000,126.000000,60.000000,20.358987,79.799479,30,0.349,47,1
767,1.000000,93.000000,70.000000,31.000000,79.799479,30,0.315,23,0

In [179]:
accuracy = diabetesCheck.score(testData, testLabel)
print("accuracy = ", accuracy * 100, "%")

accuracy =  75.0 %